spring:
  application:
    name: Crypto Authorization Server
  security:
    user:
      name: "victoria"
      password: "password"
    oauth2:
      authorizationserver:
        client:
          portfolio-client:
            registration:
              client-id: "portfolio-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
              scopes:
                - "openid"
                - "profile"
              require-authorization-consent: true
              redirect-uris:
                - "https://oauth.pstmn.io/v1/browser-callback"


